//! SeaORM store backend.

use std::any::TypeId;
use std::marker::PhantomData;
use std::str::FromStr;
use std::sync::{Arc, OnceLock};

use async_trait::async_trait;

use ferrite_orm::{db::DatabaseKind, Entity, OrmError, Pick, Store};
use fr_core::__export::inventory;
use fr_core::{AnyArc, Container, Injectable, ProviderEntry, Scope};

use sea_orm::{ActiveModelTrait, DatabaseConnection};

fn default_database_url() -> &'static str {
    // Prefer an in-memory SQLite default if the feature is enabled, otherwise
    // we require the user to supply `DATABASE_URL` explicitly for any other
    // backend (there is no portable in-memory default for Postgres/MySQL).
    #[cfg(feature = "sqlite")]
    {
        "sqlite::memory:"
    }
    #[cfg(all(not(feature = "sqlite"), any(feature = "postgres", feature = "mysql")))]
    {
        ""
    }
    #[cfg(not(any(feature = "sqlite", feature = "postgres", feature = "mysql")))]
    {
        ""
    }
}

fn validate_kind_enabled(kind: DatabaseKind) -> Result<(), OrmError> {
    let enabled = match kind {
        DatabaseKind::Sqlite => cfg!(feature = "sqlite"),
        DatabaseKind::Postgres => cfg!(feature = "postgres"),
        DatabaseKind::MySql => cfg!(feature = "mysql"),
    };
    if enabled {
        Ok(())
    } else {
        Err(OrmError::Backend(format!(
            "DATABASE_URL scheme {:?} requires `ferrite-orm-sea` feature \"{}\" to be enabled (it is currently off). Re-run `cargo add ferrite-orm-sea --features {}` or add the feature to your Cargo.toml.",
            kind,
            kind.feature_name(),
            kind.feature_name(),
        )))
    }
}

/// A [`Pick`] that builds [`SeaStore`] backends for bridged entities.
///
/// The connection string comes from the `DATABASE_URL` config key
/// (defaults to `sqlite::memory:` only when the `sqlite` feature is on).
/// Resolvable through the DI container: it depends on
/// [`fr_config::ConfigService`].
pub struct SeaPick {
    pub(crate) url: String,
}

impl SeaPick {
    #[doc(hidden)]
    pub fn deps() -> Vec<TypeId> {
        vec![TypeId::of::<fr_config::ConfigService>()]
    }

    #[doc(hidden)]
    pub fn factory(c: &Container) -> AnyArc {
        let config: Arc<fr_config::ConfigService> = c.get();
        let url = config.get_or("DATABASE_URL", default_database_url());
        match DatabaseKind::from_url(&url).and_then(validate_kind_enabled) {
            Ok(()) => Arc::new(SeaPick { url }) as AnyArc,
            Err(e) => {
                // Surface the error by returning an Arc containing the
                // diagnostic as a picker that will fail on first use (DI
                // factories are infallible at this layer; the Store trait
                // converts any problem into `OrmError::Backend`). We log a
                // clear panic message for developers so configuration bugs
                // are impossible to miss.
                panic!(
                    "ferrite-orm-sea: invalid DATABASE_URL `{url}`: {e}. \
                    If you want to use a different backend, enable the matching Cargo feature for `ferrite-orm-sea` (sqlite/postgres/mysql)."
                );
            }
        }
    }
}

impl Injectable for SeaPick {
    fn __provider_entry() -> ProviderEntry {
        ProviderEntry::new_static::<SeaPick>(
            "SeaPick",
            Scope::Singleton,
            SeaPick::deps,
            SeaPick::factory,
        )
    }
}

// Hand-rolled registration (same pattern as `InMemoryPick`).
inventory::submit! {
    ProviderEntry::new_static::<SeaPick>("SeaPick", Scope::Singleton, SeaPick::deps, SeaPick::factory)
}

/// User-facing bridge from a ferrite entity to its SeaORM entity.
pub trait ModelEntity: Entity {
    /// The SeaORM entity (generated by `DeriveEntityModel`) whose `Model` is `Self`.
    type Entity: sea_orm::EntityTrait<Model = Self>;
}

impl<E> Pick<E> for SeaPick
where
    E: Entity + ModelEntity + sea_orm::FromQueryResult,
    E::PrimaryKey: std::fmt::Display,
    E::Entity: sea_orm::EntityTrait<Model = E>,
    <E::Entity as sea_orm::EntityTrait>::PrimaryKey: sea_orm::PrimaryKeyTrait,
    <<E::Entity as sea_orm::EntityTrait>::PrimaryKey as sea_orm::PrimaryKeyTrait>::ValueType:
        FromStr + Into<sea_orm::sea_query::Value> + Send + Sync + 'static,
    <E::Entity as sea_orm::EntityTrait>::ActiveModel:
        sea_orm::ActiveModelTrait<Entity = E::Entity> + sea_orm::ActiveModelBehavior + Send + Sync,
    E: sea_orm::IntoActiveModel<<E::Entity as sea_orm::EntityTrait>::ActiveModel>,
{
    fn build(&self) -> Arc<dyn Store<E>> {
        Arc::new(SeaStore::<E>::new(self.url.clone()))
    }
}

/// A [`Store`] backed by SeaORM.
///
/// `E` must be a ferrite entity AND a SeaORM `Model` (the usual
/// `#[derive(sea_orm::DeriveEntityModel, sea_orm::DeriveIntoActiveModel)]`
/// output) bridged through `ModelEntity`. The connection is opened lazily
/// on the first operation.
pub struct SeaStore<E> {
    url: String,
    conn: OnceLock<Result<DatabaseConnection, String>>,
    _marker: PhantomData<fn() -> E>,
}

impl<E: Entity> SeaStore<E> {
    pub fn new(url: String) -> Self {
        Self {
            url,
            conn: OnceLock::new(),
            _marker: PhantomData,
        }
    }

    /// Build a store over an already-open connection (useful in tests/migrations).
    pub fn with_connection(conn: DatabaseConnection) -> Self {
        Self {
            url: String::new(),
            conn: OnceLock::from(Ok(conn)),
            _marker: PhantomData,
        }
    }

    async fn conn(&self) -> Result<&DatabaseConnection, OrmError> {
        if let Some(c) = self.conn.get() {
            return c.as_ref().map_err(|e| OrmError::Backend(e.clone()));
        }
        let result = sea_orm::Database::connect(&self.url)
            .await
            .map_err(|e| e.to_string());
        // Calls concurrent with the first one simply read whatever wins.
        let _ = self.conn.set(result);
        self.conn
            .get()
            .unwrap()
            .as_ref()
            .map_err(|e| OrmError::Backend(e.clone()))
    }
}

type SeaEntityOf<E> = <E as ModelEntity>::Entity;
type SeaModelOf<E> = <SeaEntityOf<E> as sea_orm::EntityTrait>::Model;
type SeaPkOf<E> = <SeaEntityOf<E> as sea_orm::EntityTrait>::PrimaryKey;
type SeaPkValueOf<E> = <SeaPkOf<E> as sea_orm::PrimaryKeyTrait>::ValueType;
type SeaActiveOf<E> = <SeaEntityOf<E> as sea_orm::EntityTrait>::ActiveModel;

#[async_trait]
impl<E> Store<E> for SeaStore<E>
where
    E: Entity + ModelEntity + sea_orm::FromQueryResult,
    E::PrimaryKey: std::fmt::Display,
    E::Entity: sea_orm::EntityTrait<Model = E>,
    SeaModelOf<E>: ForE,
    SeaPkOf<E>: sea_orm::PrimaryKeyTrait,
    SeaPkValueOf<E>: FromStr + Into<sea_orm::sea_query::Value> + Send + Sync + 'static,
    SeaActiveOf<E>:
        sea_orm::ActiveModelTrait<Entity = E::Entity> + sea_orm::ActiveModelBehavior + Send + Sync,
    E: sea_orm::IntoActiveModel<SeaActiveOf<E>>,
{
    async fn find_all(&self) -> Result<Vec<E>, OrmError> {
        let db = self.conn().await?;
        let rows = <E::Entity as sea_orm::EntityTrait>::find()
            .all(db)
            .await
            .map_err(|e| OrmError::Backend(e.to_string()))?;
        Ok(rows)
    }

    async fn find_by_pk(&self, pk: &str) -> Result<Option<E>, OrmError> {
        let db = self.conn().await?;
        let value: SeaPkValueOf<E> = pk.parse().map_err(|_| OrmError::Key(pk.to_string()))?;
        let row = <E::Entity as sea_orm::EntityTrait>::find_by_id(value)
            .one(db)
            .await
            .map_err(|e| OrmError::Backend(e.to_string()))?;
        Ok(row)
    }

    async fn save(&self, entity: &E) -> Result<(), OrmError> {
        let db = self.conn().await?;
        let pk_str = entity.primary_key().to_string();
        if self.find_by_pk(&pk_str).await?.is_some() {
            let active =
                <E as sea_orm::IntoActiveModel<SeaActiveOf<E>>>::into_active_model(entity.clone());
            active
                .update(db)
                .await
                .map(|_| ())
                .map_err(|e| OrmError::Backend(e.to_string()))?;
        } else {
            let active =
                <E as sea_orm::IntoActiveModel<SeaActiveOf<E>>>::into_active_model(entity.clone());
            <E::Entity as sea_orm::EntityTrait>::insert(active)
                .exec(db)
                .await
                .map(|_| ())
                .map_err(|e| OrmError::Backend(e.to_string()))?;
        }
        Ok(())
    }

    async fn delete(&self, pk: &str) -> Result<bool, OrmError> {
        let db = self.conn().await?;
        let value: SeaPkValueOf<E> = pk.parse().map_err(|_| OrmError::Key(pk.to_string()))?;
        let deleted = <E::Entity as sea_orm::EntityTrait>::delete_by_id(value)
            .exec(db)
            .await
            .map_err(|e| OrmError::Backend(e.to_string()))?;
        Ok(deleted.rows_affected > 0)
    }
}

impl<E: Entity> std::fmt::Debug for SeaStore<E> {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("SeaStore").field("url", &self.url).finish()
    }
}

/// Minimal `FromQueryResult`-style marker used to keep the where-clause tidy.
trait ForE {}
impl<T: sea_orm::FromQueryResult> ForE for T {}

#[cfg(test)]
mod tests {
    use sea_orm::entity::prelude::*;
    use sea_orm::{DeriveEntityModel, DeriveRelation, EnumIter};

    use ferrite_orm::Entity as FerriteEntity;

    use super::*;

    #[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
    #[sea_orm(table_name = "cats")]
    pub struct Model {
        #[sea_orm(primary_key)]
        pub id: i64,
        pub name: String,
    }

    impl ModelEntity for Model {
        type Entity = Entity;
    }

    impl FerriteEntity for Model {
        type PrimaryKey = i64;

        fn table_name() -> &'static str {
            "cats"
        }

        fn primary_key(&self) -> i64 {
            self.id
        }
    }

    #[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
    pub enum Relation {}

    impl ActiveModelBehavior for ActiveModel {}

    #[tokio::test]
    async fn sea_store_crud_roundtrip() {
        let backend = sea_orm::DatabaseBackend::Sqlite;
        let db = sea_orm::Database::connect("sqlite::memory:").await.unwrap();
        let schema = sea_orm::Schema::new(backend);
        let stmt = schema.create_table_from_entity(Entity);
        db.execute(&stmt).await.unwrap();

        let store = SeaStore::<Model>::with_connection(db);

        store
            .save(&Model {
                id: 1,
                name: "Milo".into(),
            })
            .await
            .unwrap();
        store
            .save(&Model {
                id: 2,
                name: "Luna".into(),
            })
            .await
            .unwrap();

        let all = store.find_all().await.unwrap();
        assert_eq!(all.len(), 2, "expected two rows, got {all:?}");

        let one = store.find_by_pk("1").await.unwrap().unwrap();
        assert_eq!(one.name, "Milo");
        assert!(store.find_by_pk("99").await.unwrap().is_none());

        assert!(store.delete("2").await.unwrap());
        assert!(!store.delete("2").await.unwrap());
    }
}
