//! Ferrite Swagger — drop-in OpenAPI 3.x generation + Swagger UI for Ferrite.
//!
//! Minimal NestJS `@nestjs/swagger` equivalent. Register schema fragments
//! globally via [`submit_fragment!`] at compile time, add
//! [`SwaggerModule`] to your imports, then visit `/docs` in a browser.
//!
//! # Example
//!
//! ```ignore
//! use ferrite_framework::module;
//! use ferrite_swagger::{SwaggerModule, submit_fragment};
//!
//! submit_fragment! { |api: &mut utoipa::openapi::OpenApi| {
//!     use utoipa::openapi::path::{HttpMethod, OperationBuilder, PathItem};
//!     let op = OperationBuilder::new().summary(Some("hello world")).build();
//!     let item = PathItem::new(HttpMethod::Get, op);
//!     api.paths.paths.insert("/hello".into(), item);
//! }}
//!
//! #[module(imports = [SwaggerModule])]
//! pub struct AppModule;
//! ```
//!
//! Output endpoints:
//!
//! * `GET /openapi.json` — compiled OpenAPI document
//! * `GET /docs` — Swagger UI (loaded over CDN — internet required)
//! * `GET /docs/` — same as above

use std::sync::Arc;

use ferrite_config::ConfigService;
use ferrite_framework::__export::inventory;
use ferrite_framework::all_controller_routes;
use ferrite_framework::extract::Json as HttpJson;
use ferrite_macros::{controller, impl_controller, inject, injectable, module};
use serde::Serialize;
use utoipa::openapi::path::{HttpMethod, OperationBuilder, PathItem};
use utoipa::openapi::request_body::RequestBodyBuilder;
use utoipa::openapi::security::{HttpAuthScheme, HttpBuilder, SecurityRequirement, SecurityScheme};
use utoipa::openapi::{
    ComponentsBuilder, Content, InfoBuilder, OpenApi, Ref, Required, ResponseBuilder, ServerBuilder,
};

/// Runtime configuration for the Swagger subsystem. Values are read from the
/// environment via [`ConfigService`]:
///
/// * `SWAGGER_TITLE` — default `"Ferrite API"`
/// * `SWAGGER_VERSION` — default `"0.1.0"`
/// * `SWAGGER_DESCRIPTION` — default `"Generated by Ferrite"`
/// * `SWAGGER_SERVER_URL` — e.g. `"http://localhost:3000"`; when unset the
///   `servers` field is omitted entirely.
#[derive(Debug, Clone)]
pub struct SwaggerConfig {
    pub title: String,
    pub version: String,
    pub description: String,
    pub server_url: Option<String>,
}

impl SwaggerConfig {
    pub fn load() -> Self {
        let cfg = ConfigService::load();
        Self {
            title: cfg.get_or("SWAGGER_TITLE", "Ferrite API"),
            version: cfg.get_or("SWAGGER_VERSION", "0.1.0"),
            description: cfg.get_or("SWAGGER_DESCRIPTION", "Generated by Ferrite"),
            server_url: cfg.get("SWAGGER_SERVER_URL"),
        }
    }
}

impl Default for SwaggerConfig {
    fn default() -> Self {
        Self::load()
    }
}

/// A single OpenAPI schema fragment. Each crate registers closures that
/// mutate a shared [`OpenApi`] document. Order is intentionally irrelevant.
pub struct SwaggerFragment {
    #[doc(hidden)]
    pub apply: fn(&mut OpenApi),
}

inventory::collect!(SwaggerFragment);

/// Register an `Fn(&mut OpenApi)` closure as a compile-time fragment. Use
/// this to add paths, schemas, security blocks from any crate.
#[macro_export]
macro_rules! submit_fragment {
    ($e:expr) => {
        ::ferrite_framework::__export::inventory::submit! {
            $crate::SwaggerFragment {
                apply: (|api: &mut utoipa::openapi::OpenApi| { $e(api); })
                    as fn(&mut utoipa::openapi::OpenApi),
            }
        }
    };
}

/// Aggregate base configuration + registered fragments into an [`OpenApi`].
pub fn build_openapi(config: &SwaggerConfig) -> OpenApi {
    let info = InfoBuilder::new()
        .title(config.title.clone())
        .version(config.version.clone())
        .description(Some(config.description.clone()))
        .build();
    let mut api = OpenApi::new(info, utoipa::openapi::Paths::new());
    if let Some(url) = &config.server_url {
        let server = ServerBuilder::new().url(url.clone()).build();
        api.servers = Some(vec![server]);
    }
    // Register JWT Bearer global security scheme (Authorize button appears).
    let bearer_scheme = SecurityScheme::Http(
        HttpBuilder::new()
            .scheme(HttpAuthScheme::Bearer)
            .bearer_format("JWT")
            .description(Some(
                "Obtain a token via `POST /auth/login` or `POST /auth/register`, then click Authorize and enter: Bearer <token>",
            ))
            .build(),
    );
    let mut comps = ComponentsBuilder::new().build();
    comps
        .security_schemes
        .insert("bearer".into(), bearer_scheme);
    api.components = Some(comps);

    // Auto-discover routes from inventory ControllerRoutes (#[impl_controller]).
    for cr in all_controller_routes() {
        let prefix = cr.prefix.trim_end_matches('/');
        for route in cr.routes {
            let full_path = if route.path.trim_end_matches('/').is_empty() {
                if prefix.is_empty() {
                    "/".to_string()
                } else {
                    format!("{prefix}/")
                }
            } else if prefix.is_empty() {
                route.path.to_string()
            } else {
                format!("{prefix}{}", route.path)
            };
            let (method, method_lower) = match route.method {
                "GET" => (HttpMethod::Get, "get"),
                "POST" => (HttpMethod::Post, "post"),
                "PUT" => (HttpMethod::Put, "put"),
                "PATCH" => (HttpMethod::Patch, "patch"),
                "DELETE" => (HttpMethod::Delete, "delete"),
                "HEAD" => (HttpMethod::Head, "head"),
                "OPTIONS" => (HttpMethod::Options, "options"),
                _ => (HttpMethod::Get, "get"),
            };
            let summary = format!("{} {}", method_lower.to_uppercase(), full_path);
            let ok = ResponseBuilder::new().description("OK").build();
            let not_found = ResponseBuilder::new().description("Not Found").build();
            let unauthorized = ResponseBuilder::new()
                .description("Unauthorized (missing or invalid JWT)")
                .build();
            let bad_request = ResponseBuilder::new()
                .description("Bad Request (invalid JSON body / validation error)")
                .build();

            let mut op = OperationBuilder::new()
                .operation_id(Some(format!(
                    "{}_{}",
                    full_path
                        .trim_start_matches('/')
                        .replace(['/', '{', '}', ':', '-'], "_"),
                    method_lower
                )))
                .summary(Some(summary))
                .response("200", ok.clone())
                .response("400", bad_request.clone())
                .response("404", not_found.clone());

            // Attach request body (DTO type list from RouteSpec).
            let body_types: Vec<&str> = route
                .request_body_types
                .split(',')
                .map(|s| s.trim())
                .filter(|s| !s.is_empty())
                .collect();
            for fq_name in &body_types {
                let short = fq_name.split("::").last().unwrap_or(fq_name);
                let schema_short = short.split(';').next().unwrap_or(short);
                let rb = RequestBodyBuilder::new()
                    .description(Some(format!("JSON body — `{schema_short}`")))
                    .required(Some(Required::True))
                    .content(
                        "application/json",
                        Content::new(Some(Ref::from_schema_name(schema_short))),
                    )
                    .build();
                op = op.request_body(Some(rb));
            }

            // Attach security (Authorize requirement) + 401 response when any guard declared.
            let guards: Vec<&str> = route
                .guard_types
                .split(',')
                .map(|s| s.trim())
                .filter(|s| !s.is_empty())
                .collect();
            if !guards.is_empty() {
                op = op.response("401", unauthorized.clone());
                let sec = SecurityRequirement::new("bearer", Vec::<String>::new());
                op = op.securities(Some(vec![sec]));
            }

            let op_built = op.build();
            let item = PathItem::new(method, op_built);
            api.paths.paths.insert(full_path, item);
        }
    }
    for fragment in inventory::iter::<SwaggerFragment> {
        (fragment.apply)(&mut api);
    }
    api
}

/// JSON envelope returned by `/openapi.json`.
#[derive(Debug, Clone)]
pub struct OpenApiDocument(pub serde_json::Value);

impl Serialize for OpenApiDocument {
    fn serialize<S: serde::Serializer>(&self, s: S) -> Result<S::Ok, S::Error> {
        self.0.serialize(s)
    }
}

impl OpenApiDocument {
    pub fn build(config: &SwaggerConfig) -> Self {
        let api = build_openapi(config);
        let value = serde_json::to_value(&api).unwrap_or_else(|_| serde_json::json!({}));
        Self(value)
    }
}

/// Injectable service that owns the [`SwaggerConfig`] snapshot and can build
/// the compiled [`OpenApiDocument`] on demand.
#[injectable]
pub struct SwaggerService {
    config: SwaggerConfig,
    _anchor: u8,
}

impl Default for SwaggerService {
    fn default() -> Self {
        Self::new()
    }
}

impl SwaggerService {
    #[inject]
    pub fn new() -> Self {
        Self {
            config: SwaggerConfig::load().into(),
            _anchor: Arc::new(0),
        }
    }
    pub fn config(&self) -> &SwaggerConfig {
        &self.config
    }
    pub fn document(&self) -> OpenApiDocument {
        OpenApiDocument::build(&self.config)
    }
    pub fn openapi(&self) -> OpenApi {
        build_openapi(&self.config)
    }
}

/// The canonical HTML page served at `/docs` and `/docs/index.html`. It uses
/// the public Swagger UI CDN so no static assets are bundled.
fn swagger_index_html() -> String {
    r#"<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<title>Ferrite — Swagger UI</title>
<link rel="stylesheet" href="https://unpkg.com/swagger-ui-dist@5/swagger-ui.css" />
<style>html { box-sizing: border-box; overflow: -moz-scrollbars-vertical; margin: 0; padding: 0; }
*, *:before, *:after { box-sizing: inherit; }
body { margin: 0; background: #fafafa; }</style>
</head>
<body><div id="swagger-ui"></div>
<script src="https://unpkg.com/swagger-ui-dist@5/swagger-ui-bundle.js" crossorigin></script>
<script src="https://unpkg.com/swagger-ui-dist@5/swagger-ui-standalone-preset.js" crossorigin></script>
<script>
window.ui = SwaggerUIBundle({
  url: "/openapi.json",
  dom_id: '#swagger-ui',
  deepLinking: true,
  presets: [SwaggerUIBundle.presets.apis, SwaggerUIStandalonePreset],
  plugins: [SwaggerUIBundle.plugins.DownloadUrl],
  layout: "StandaloneLayout"
});
</script>
</body>
</html>"#
    .into()
}

/// HTTP controller exposing OpenAPI JSON + Swagger UI CDN HTML.
#[controller("")]
pub struct SwaggerController {
    service: SwaggerService,
}

#[impl_controller]
impl SwaggerController {
    #[inject]
    pub fn new(service: SwaggerService) -> Self {
        Self { service }
    }

    #[ferrite_macros::get("/openapi.json")]
    pub async fn openapi_json(&self) -> HttpJson<OpenApiDocument> {
        HttpJson(self.service.document())
    }

    #[ferrite_macros::get("/docs")]
    pub async fn docs_root(&self) -> axum::response::Html<String> {
        axum::response::Html(swagger_index_html())
    }

    #[ferrite_macros::get("/docs/")]
    pub async fn docs_slash(&self) -> axum::response::Html<String> {
        axum::response::Html(swagger_index_html())
    }
}

/// Ferrite module that mounts Swagger routes on your app. Just add
/// `imports = [SwaggerModule]` to your root `#[module]`.
#[module(
    controllers = [SwaggerController],
    providers = [SwaggerService],
)]
pub struct SwaggerModule;

#[cfg(test)]
mod tests {
    use super::*;

    submit_fragment! { |api: &mut utoipa::openapi::OpenApi| {
        use utoipa::openapi::path::{HttpMethod, OperationBuilder, PathItem};
        let op = OperationBuilder::new()
            .summary(Some("ping"))
            .build();
        let item = PathItem::new(HttpMethod::Get, op);
        api.paths.paths.insert("/ping".into(), item);
    }}

    #[test]
    fn build_includes_custom_fragment() {
        let cfg = SwaggerConfig {
            title: "Test".into(),
            version: "1.0".into(),
            description: "d".into(),
            server_url: None,
        };
        let api = build_openapi(&cfg);
        assert_eq!(api.info.title, "Test");
        assert!(api.paths.paths.contains_key("/ping"));
    }

    #[test]
    fn document_serializes_valid_json() {
        let cfg = SwaggerConfig {
            title: "T".into(),
            version: "0.1".into(),
            description: "".into(),
            server_url: None,
        };
        let doc = OpenApiDocument::build(&cfg);
        let json = serde_json::to_string(&doc).unwrap();
        assert!(json.contains("\"title\":\"T\""));
        assert!(json.contains("\"openapi\""));
    }

    #[test]
    fn docs_html_mentions_bundle() {
        let html = swagger_index_html();
        assert!(html.contains("swagger-ui-bundle"));
        assert!(html.contains("/openapi.json"));
    }
}
