[package]
name = "mono-ws-chat"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
ferrite-framework = { workspace = true }
fr-core = { workspace = true }
ferrite-macros = { workspace = true }
ferrite-http = { workspace = true }
ferrite-config = { workspace = true }
ferrite-validation = { workspace = true }
ferrite-health = { workspace = true }
ferrite-auth-jwt = { workspace = true }
ferrite-swagger = { workspace = true }
ferrite-throttler = { workspace = true }
ferrite-ws = { workspace = true }

serde = { workspace = true }
serde_json = { workspace = true }
anyhow = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
async-trait = { workspace = true }
futures-util = { workspace = true }
tower-http = { workspace = true }
axum = { workspace = true }
inventory = { workspace = true }

dashmap = { workspace = true }
rand = { workspace = true }
uuid = { workspace = true }
chrono = { workspace = true }
utoipa = { workspace = true }
