//! Module abstraction and descriptors.

use std::any::TypeId;

/// Compile-time metadata emitted by the `#[module]` macro.
#[derive(Debug, Default, Clone)]
pub struct ModuleDescriptor {
    pub name: String,
    /// `TypeId`s of imported modules.
    pub imports: Vec<TypeId>,
    /// `TypeId`s of controllers owned by this module.
    pub controllers: Vec<TypeId>,
    /// `TypeId`s of providers owned by this module.
    pub providers: Vec<TypeId>,
    /// `TypeId`s of providers re-exported to importing modules.
    pub exports: Vec<TypeId>,
    /// `TypeId`s of middleware applicable to the whole module.
    pub middleware: Vec<TypeId>,
    /// Whether this module is `#[module(global)]`.
    pub global: bool,
}

/// Every module type implements this trait (generated by `#[module]`).
pub trait Module: 'static {
    /// Build the descriptor for this module.
    fn __module_descriptor() -> ModuleDescriptor {
        ModuleDescriptor::default()
    }
}

/// A module entry registered via `inventory`.
#[derive(Clone)]
pub struct ModuleEntry {
    pub ty: TypeId,
    pub name: &'static str,
    pub descriptor_fn: fn() -> ModuleDescriptor,
}

impl ModuleEntry {
    /// Build an entry for the given module type.
    pub const fn new<T: Module>(name: &'static str) -> Self {
        Self {
            ty: TypeId::of::<T>(),
            name,
            descriptor_fn: <T as Module>::__module_descriptor,
        }
    }
}
